name: como
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - certifi=2023.11.17
  - ffmpeg=4.3
  - freetype=2.10.4
  - intel-openmp=2021.3.0
  - jpeg=9b
  - lame=3.100
  - lcms2=2.12
  - libffi=3.3
  - libiconv=1.15
  - libpng=1.6.37
  - libtiff=4.2.0
  - libuv=1.40.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - ninja=1.10.2
  - olefile=0.46
  - openjpeg=2.3.0
  - openssl=1.1.1w
  - pip=21.0.1
  - python=3.8.11
  - setuptools=52.0.0
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.10
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
      - absl-py==0.13.0
      - aiofiles==23.2.1
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - altair==5.2.0
      - annotated-types==0.6.0
      - antlr4-python3-runtime==4.9.3
      - anyio==3.7.1
      - appdirs==1.4.4
      - async-timeout==4.0.3
      - attrs==23.2.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - cachetools==4.2.2
      - charset-normalizer==2.0.4
      - chumpy==0.70
      - click==8.1.7
      - colorama==0.4.6
      - colorlog==6.8.0
      - cycler==0.10.0
      - dataclasses-json==0.6.3
      - decorator==5.0.9
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - einops==0.7.0
      - exceptiongroup==1.2.0
      - fastapi==0.109.2
      - ffmpy==0.3.1
      - filelock==3.13.1
      - freetype-py==2.4.0
      - frozenlist==1.4.1
      - fsspec==2023.12.2
      - ftfy==6.1.1
      - gdown==4.7.1
      - gitdb==4.0.11
      - gitpython==3.1.40
      - google-auth==1.35.0
      - google-auth-oauthlib==0.4.5
      - gradio==4.17.0
      - gradio-client==0.9.0
      - gradio-multimodalchatbot==0.0.1
      - greenlet==3.0.3
      - grpcio==1.39.0
      - h11==0.14.0
      - h5py==3.10.0
      - httpcore==1.0.2
      - httpx==0.26.0
      - huggingface-hub==0.20.2
      - hydra-colorlog==1.2.0
      - hydra-core==1.3.2
      - idna==3.2
      - imageio==2.9.0
      - imageio-ffmpeg==0.4.9
      - importlib-resources==6.1.1
      - ipdb==0.13.9
      - ipython==7.26.0
      - ipython-genutils==0.2.0
      - jedi==0.18.0
      - jinja2==3.1.2
      - joblib==1.0.1
      - jsonpatch==1.33
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.3.1
      - langchain==0.1.0
      - langchain-community==0.0.12
      - langchain-core==0.1.10
      - langsmith==0.0.80
      - lightning-utilities==0.10.1
      - mapbox-earcut==1.0.1
      - markdown==3.3.4
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - marshmallow==3.20.2
      - matplotlib==3.4.3
      - matplotlib-inline==0.1.2
      - mdurl==0.1.2
      - moviepy==0.2.3.1
      - mpmath==1.3.0
      - multidict==6.0.4
      - mypy-extensions==1.0.0
      - networkx==3.1
      - numpy==1.21.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12
      - nvidia-cuda-nvrtc-cu12
      - nvidia-cuda-runtime-cu12
      - nvidia-cudnn-cu12
      - nvidia-cufft-cu12
      - nvidia-curand-cu12
      - nvidia-cusolver-cu12
      - nvidia-cusparse-cu12
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12
      - nvidia-nvtx-cu12
      - oauthlib==3.1.1
      - omegaconf==2.3.0
      - openai==0.28.0
      - opencv-python==4.9.0.80
      - orjson==3.9.13
      - packaging==23.2
      - pandas==1.3.2
      - parso==0.8.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.2.0
      - pkgutil-resolve-name==1.3.10
      - prompt-toolkit==3.0.20
      - protobuf==3.17.3
      - psutil==5.9.7
      - ptyprocess==0.7.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - pydeprecate==0.3.2
      - pydub==0.25.1
      - pyglet==2.0.10
      - pygments==2.17.2
      - pyopengl==3.1.0
      - pyparsing==2.4.7
      - pyrender==0.1.45
      - pysocks==1.7.1
      - python-dateutil==2.8.2
      - python-multipart==0.0.7
      - pytorch-lightning==2.1.3
      - pytz==2021.1
      - pyyaml==5.4.1
      - referencing==0.33.0
      - regex==2023.12.25
      - requests==2.26.0
      - requests-oauthlib==1.3.0
      - rich==13.7.0
      - rpds-py==0.17.1
      - rsa==4.7.2
      - ruff==0.2.1
      - safetensors==0.4.1
      - scikit-learn==0.24.2
      - scipy==1.7.1
      - semantic-version==2.10.0
      - sentry-sdk==1.39.1
      - setproctitle==1.3.3
      - shapely==2.0.2
      - shellingham==1.5.4
      - shortuuid==1.0.11
      - sklearn==0.0
      - smmap==5.0.1
      - smplx==0.1.28
      - sniffio==1.3.0
      - soupsieve==2.5
      - sqlalchemy==2.0.25
      - starlette==0.36.3
      - sympy==1.12
      - tenacity==8.2.3
      - tensorboard==2.6.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.0
      - threadpoolctl==2.2.0
      - tokenizers==0.15.0
      - toml==0.10.2
      - tomlkit==0.12.0
      - toolz==0.12.1
      - torch==2.1.2
      - torchaudio==2.1.2
      - torchmetrics==0.7.0
      - torchvision==0.16.2
      - tqdm==4.62.2
      - traitlets==5.0.5
      - transformers==4.36.2
      - trimesh==4.0.9
      - triton==2.1.0
      - typer==0.9.0
      - typing-extensions==4.9.0
      - typing-inspect==0.9.0
      - urllib3==1.26.18
      - uvicorn==0.27.0.post1
      - wandb==0.16.1
      - wcwidth==0.2.5
      - websockets==11.0.3
      - werkzeug==2.0.1
      - yarl==1.9.4
      - zipp==3.17.0
      - git+https://github.com/openai/CLIP.git
      - git+https://github.com/nghorbani/human_body_prior
